# Base Image
FROM python:3.10-slim

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install pytest
RUN pip install pytest
# Copy application code
COPY . .

# Command to start the notification worker
CMD ["python", "notification.py"]
