
services:
  # Microservices
  micro_event:
    build: ./micro_event
    ports:
      - "5001:5000"
      
  micro_profile:
    build: ./micro_profile
    ports:
      - "5002:5000"
      
  micro_request:
    build: ./micro_request
    ports:
      - "5003:5000"
      
  micro_schedule:
    build: ./micro_schedule
    ports:
      - "5004:5000"
      

  complex_view_schedule:
    build: ./complex_service(staff)
    ports:
      - "5005:5000"




volumes:
  db_data: