
networks:
  worknest_default:
    driver: bridge

volumes:
  rabbitmq_data:
  db_data:

services:
  # Microservices
  micro_event:
    build: 
      context: ./micro_event
    command: python micro_event.py
    environment:
      - FLASK_ENV=development
    ports:
      - "5001:5000"
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  micro_profile:
    build: 
      context: ./micro_profile
    command: python micro_profile.py
    environment:
      - FLASK_ENV=development
    ports:
      - "5002:5000"
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  micro_request:
    build: 
      context: ./micro_request
    command: python micro_request.py
    environment:
      - FLASK_ENV=development
    ports:
      - "5003:5000"
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  micro_schedule:
    build: 
      context: ./micro_schedule
    command: python micro_schedule.py
    environment:
      - FLASK_ENV=development
    ports:
      - "5004:5000"
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env
      

  complex_view_schedule:
    build:
      context: ./complex_service_staff
    command: python complex_view_schedule.py
    environment:
      - FLASK_ENV=development
    ports:
      - "5005:5000"
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    env_file:
      - .env
    networks:
    - worknest_default

  micro_notification:
    build:
      context: ./micro_notification  
    command: python notification.py
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  micro_approval:
    build:
      context: ./micro_approval 
    command: python approval_service.py
    depends_on:
      - rabbitmq
    environment:
      - FLASK_ENV=development
    ports:
      - "5006:5000"  
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env


  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - worknest_default