
networks:
  worknest_default:
    driver: bridge

volumes:
  rabbitmq_data:
  db_data:

services:
  # Microservices
  micro_event:
    build: ./micro_event
    ports:
      - "5001:5000"
    env_file:
      - .env
      
  micro_profile:
    build: ./micro_profile
    ports:
      - "5002:5000"
    env_file:
      - .env
      
  micro_request:
    build: ./micro_request
    ports:
      - "5003:5000"
    env_file:
      - .env
      
  micro_schedule:
    build: ./micro_schedule
    ports:
      - "5004:5000"
    env_file:
      - .env
      

  complex_view_schedule:
    build: ./complex_service_staff
    ports:
      - "5005:5000"
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    env_file:
      - .env
    networks:
    - worknest_default

  micro_notification:
    build:
      context: ./micro_notification  
    command: python notification.py
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env

  micro_approval:
    build:
      context: ./micro_approval 
    command: python approval_service.py
    depends_on:
      - rabbitmq
    environment:
      - FLASK_ENV=development
    ports:
      - "5006:5000"  
    restart: always
    networks:
      - worknest_default
    env_file:
      - .env


