# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variable to ensure output is flushed immediately
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy requirements file first to leverage Docker caching
COPY requirements.txt ./

# Install Python dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Install pytest
RUN pip install pytest

# Copy the current directory contents into the container
COPY . .

# Set PYTHONPATH to include the src directory
ENV PYTHONPATH=/usr/src

# Expose the Flask port (default is 5006)
EXPOSE 5006  

# Command to run the app
CMD ["python", "approval_service.py"]
