# Step 1: Build the React app
# Use an official Node.js image to build the app
FROM node:20-alpine AS build

# Set working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock (or package-lock.json) files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application source code
COPY . .

# Build the application for production
RUN yarn build


# Expose port 80
EXPOSE 3000

# Step 7: Run the app in development mode using `yarn dev`
CMD ["yarn", "dev"]
