version: '3.8'

networks:
  worknest_default:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  micro_approval:
    build:
      context: ./src/app/backend/micro_approval
    command: python approval_service.py
    depends_on:
      - rabbitmq
    environment:
      - FLASK_ENV=development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5005:5005"  # Exposing approval service on port 5005
    networks:
      - worknest_default
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - worknest_default
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  micro_notification:
    build:
      context: ./src/app/backend/micro_notification
    command: python notification.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - worknest_default
    restart: always

