FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app/backend/micro_schedule

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install PostgreSQL development libraries and other dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Install pytest
RUN pip install pytest

# Copy the entire project into the /app directory
COPY . .

# Expose the port your app runs on
EXPOSE 5004

# Set environment variables
ENV FLASK_APP=micro_schedule.py
ENV FLASK_ENV=development

# Set PYTHONPATH to include the src directory
ENV PYTHONPATH=/app/src

# Run the application
CMD ["python", "micro_schedule.py"]