FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app/backend/micro_request

# Copy the requirements.txt file into the container
COPY requirements.txt .
# Install PostgreSQL development libraries and other dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Install pytest
RUN pip install pytest

# Copy the current directory contents into the container at /app
COPY . .

# Expose the port your app runs on
EXPOSE 5003

# Set environment variables
ENV FLASK_APP=micro_request.py
ENV FLASK_ENV=development

# Run the application
CMD ["python", "micro_request.py"]