name: CI/CD Pipeline

on:
  push:
    branches:
      - SCRUMS-38-Integrating-EC2-containers  # Change trigger to the Scrum branch
  pull_request:
    branches:
      - SCRUMS-38-Integrating-EC2-containers  # Change trigger to the Scrum branch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increase timeout

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        options: --memory=1g  # Limit memory to 1GB for the Postgres service

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Generate .env file
      run: |
        echo "SQLALCHEMY_DATABASE_URI='postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/postgres'" > worknest/src/app/backend/.env

    # Start and test backend-micro_profile-1 container
    - name: Start backend-micro_profile container
      run: docker compose --env-file worknest/src/app/backend/.env -f worknest/src/app/backend/compose.yaml up -d backend-micro_profile-1

    - name: Run tests for backend-micro_profile
      run: docker exec backend-micro_profile-1 pytest

    - name: Shut down backend-micro_profile container
      run: docker compose down backend-micro_profile-1

    # Start and test backend-micro_event-1 container
    - name: Start backend-micro_event container
      run: docker compose --env-file worknest/src/app/backend/.env -f worknest/src/app/backend/compose.yaml up -d backend-micro_event-1

    - name: Run tests for backend-micro_event
      run: docker exec backend-micro_event-1 pytest

    - name: Shut down backend-micro_event container
      run: docker compose down backend-micro_event-1

    # Start and test backend-micro_request-1 container
    - name: Start backend-micro_request container
      run: docker compose --env-file worknest/src/app/backend/.env -f worknest/src/app/backend/compose.yaml up -d backend-micro_request-1

    - name: Run tests for backend-micro_request
      run: docker exec backend-micro_request-1 pytest

    - name: Shut down backend-micro_request container
      run: docker compose down backend-micro_request-1

    # Start and test backend-micro_schedule-1 container
    - name: Start backend-micro_schedule container
      run: docker compose --env-file worknest/src/app/backend/.env -f worknest/src/app/backend/compose.yaml up -d backend-micro_schedule-1

    - name: Run tests for backend-micro_schedule
      run: docker exec backend-micro_schedule-1 pytest

    - name: Shut down backend-micro_schedule container
      run: docker compose down backend-micro_schedule-1

    # Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14'

    - name: Install Node.js dependencies
      run: yarn install

    # Run Jest tests
    - name: Run Jest tests
      run: yarn run jest