name: CI/CD Pipeline

on:
  push:
    branches:
      - SCRUMS-38-Integrating-EC2-containers  # Change trigger to the Scrum branch
  pull_request:
    branches:
      - SCRUMS-38-Integrating-EC2-containers  # Change trigger to the Scrum branch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a reasonable timeout (10 minutes here)

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        options: --memory=1g  # Limit memory to 1GB for the Postgres service

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Add Swap Space
    - name: Add swap space
      run: |
        sudo fallocate -l 8G /swapfile  # Allocate 8GB of swap space
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show  # Show swap summary


    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Generate .env file
      run: |
          echo "SQLALCHEMY_DATABASE_URI='postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}localhost:5432/postgres'" > worknest/src/app/backend/.env
        
    # # Install PostgreSQL development headers (libpq-dev)
    # - name: Install dependencies for psycopg2
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libpq-dev gcc


    # Build Docker images (if using Docker)
    - name: Build Docker image
      run: |
        docker compose  --env-file worknest/src/app/backend/.env -f worknest/src/app/backend/compose.yaml up -d
         # Run tests in microservices
        docker exec backend-micro_profile-1  pytest
        docker exec backend-micro_event-1  pytest
        docker exec backend-micro_request-1  pytest
        docker exec backend-micro_schedule-1  pytest
  
   # Shut down containers after Python tests
    - name: Shut down Docker containers
      run: docker compose down

    # Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14'

    - name: Install Node.js dependencies
      run: yarn install

    # Run Jest tests after Python tests
    - name: Run Jest tests
      run: yarn run jest




  
